/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shift_8 (
    input [1:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] shifted
  );
  
  
  
  always @* begin
    
    case (alufn)
      2'h0: begin
        shifted = a << b;
      end
      2'h1: begin
        shifted = a >> b;
      end
      2'h3: begin
        shifted = $signed(a) >>> b;
      end
      default: begin
        shifted = 8'h00;
      end
    endcase
  end
endmodule
