/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sixtnbitfa_6 (
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] sum,
    input alufn,
    output reg v,
    output reg z,
    output reg n
  );
  
  
  
  wire [1-1:0] M_fa1_sum;
  wire [1-1:0] M_fa1_carryout;
  reg [1-1:0] M_fa1_a;
  reg [1-1:0] M_fa1_b;
  reg [1-1:0] M_fa1_c;
  fa_11 fa1 (
    .a(M_fa1_a),
    .b(M_fa1_b),
    .c(M_fa1_c),
    .sum(M_fa1_sum),
    .carryout(M_fa1_carryout)
  );
  
  wire [1-1:0] M_fa2_sum;
  wire [1-1:0] M_fa2_carryout;
  reg [1-1:0] M_fa2_a;
  reg [1-1:0] M_fa2_b;
  reg [1-1:0] M_fa2_c;
  fa_11 fa2 (
    .a(M_fa2_a),
    .b(M_fa2_b),
    .c(M_fa2_c),
    .sum(M_fa2_sum),
    .carryout(M_fa2_carryout)
  );
  
  wire [1-1:0] M_fa3_sum;
  wire [1-1:0] M_fa3_carryout;
  reg [1-1:0] M_fa3_a;
  reg [1-1:0] M_fa3_b;
  reg [1-1:0] M_fa3_c;
  fa_11 fa3 (
    .a(M_fa3_a),
    .b(M_fa3_b),
    .c(M_fa3_c),
    .sum(M_fa3_sum),
    .carryout(M_fa3_carryout)
  );
  
  wire [1-1:0] M_fa4_sum;
  wire [1-1:0] M_fa4_carryout;
  reg [1-1:0] M_fa4_a;
  reg [1-1:0] M_fa4_b;
  reg [1-1:0] M_fa4_c;
  fa_11 fa4 (
    .a(M_fa4_a),
    .b(M_fa4_b),
    .c(M_fa4_c),
    .sum(M_fa4_sum),
    .carryout(M_fa4_carryout)
  );
  
  wire [1-1:0] M_fa5_sum;
  wire [1-1:0] M_fa5_carryout;
  reg [1-1:0] M_fa5_a;
  reg [1-1:0] M_fa5_b;
  reg [1-1:0] M_fa5_c;
  fa_11 fa5 (
    .a(M_fa5_a),
    .b(M_fa5_b),
    .c(M_fa5_c),
    .sum(M_fa5_sum),
    .carryout(M_fa5_carryout)
  );
  
  wire [1-1:0] M_fa6_sum;
  wire [1-1:0] M_fa6_carryout;
  reg [1-1:0] M_fa6_a;
  reg [1-1:0] M_fa6_b;
  reg [1-1:0] M_fa6_c;
  fa_11 fa6 (
    .a(M_fa6_a),
    .b(M_fa6_b),
    .c(M_fa6_c),
    .sum(M_fa6_sum),
    .carryout(M_fa6_carryout)
  );
  
  wire [1-1:0] M_fa7_sum;
  wire [1-1:0] M_fa7_carryout;
  reg [1-1:0] M_fa7_a;
  reg [1-1:0] M_fa7_b;
  reg [1-1:0] M_fa7_c;
  fa_11 fa7 (
    .a(M_fa7_a),
    .b(M_fa7_b),
    .c(M_fa7_c),
    .sum(M_fa7_sum),
    .carryout(M_fa7_carryout)
  );
  
  wire [1-1:0] M_fa8_sum;
  wire [1-1:0] M_fa8_carryout;
  reg [1-1:0] M_fa8_a;
  reg [1-1:0] M_fa8_b;
  reg [1-1:0] M_fa8_c;
  fa_11 fa8 (
    .a(M_fa8_a),
    .b(M_fa8_b),
    .c(M_fa8_c),
    .sum(M_fa8_sum),
    .carryout(M_fa8_carryout)
  );
  
  wire [1-1:0] M_fa9_sum;
  wire [1-1:0] M_fa9_carryout;
  reg [1-1:0] M_fa9_a;
  reg [1-1:0] M_fa9_b;
  reg [1-1:0] M_fa9_c;
  fa_11 fa9 (
    .a(M_fa9_a),
    .b(M_fa9_b),
    .c(M_fa9_c),
    .sum(M_fa9_sum),
    .carryout(M_fa9_carryout)
  );
  
  wire [1-1:0] M_fa10_sum;
  wire [1-1:0] M_fa10_carryout;
  reg [1-1:0] M_fa10_a;
  reg [1-1:0] M_fa10_b;
  reg [1-1:0] M_fa10_c;
  fa_11 fa10 (
    .a(M_fa10_a),
    .b(M_fa10_b),
    .c(M_fa10_c),
    .sum(M_fa10_sum),
    .carryout(M_fa10_carryout)
  );
  
  wire [1-1:0] M_fa11_sum;
  wire [1-1:0] M_fa11_carryout;
  reg [1-1:0] M_fa11_a;
  reg [1-1:0] M_fa11_b;
  reg [1-1:0] M_fa11_c;
  fa_11 fa11 (
    .a(M_fa11_a),
    .b(M_fa11_b),
    .c(M_fa11_c),
    .sum(M_fa11_sum),
    .carryout(M_fa11_carryout)
  );
  
  wire [1-1:0] M_fa12_sum;
  wire [1-1:0] M_fa12_carryout;
  reg [1-1:0] M_fa12_a;
  reg [1-1:0] M_fa12_b;
  reg [1-1:0] M_fa12_c;
  fa_11 fa12 (
    .a(M_fa12_a),
    .b(M_fa12_b),
    .c(M_fa12_c),
    .sum(M_fa12_sum),
    .carryout(M_fa12_carryout)
  );
  
  wire [1-1:0] M_fa13_sum;
  wire [1-1:0] M_fa13_carryout;
  reg [1-1:0] M_fa13_a;
  reg [1-1:0] M_fa13_b;
  reg [1-1:0] M_fa13_c;
  fa_11 fa13 (
    .a(M_fa13_a),
    .b(M_fa13_b),
    .c(M_fa13_c),
    .sum(M_fa13_sum),
    .carryout(M_fa13_carryout)
  );
  
  wire [1-1:0] M_fa14_sum;
  wire [1-1:0] M_fa14_carryout;
  reg [1-1:0] M_fa14_a;
  reg [1-1:0] M_fa14_b;
  reg [1-1:0] M_fa14_c;
  fa_11 fa14 (
    .a(M_fa14_a),
    .b(M_fa14_b),
    .c(M_fa14_c),
    .sum(M_fa14_sum),
    .carryout(M_fa14_carryout)
  );
  
  wire [1-1:0] M_fa15_sum;
  wire [1-1:0] M_fa15_carryout;
  reg [1-1:0] M_fa15_a;
  reg [1-1:0] M_fa15_b;
  reg [1-1:0] M_fa15_c;
  fa_11 fa15 (
    .a(M_fa15_a),
    .b(M_fa15_b),
    .c(M_fa15_c),
    .sum(M_fa15_sum),
    .carryout(M_fa15_carryout)
  );
  
  wire [1-1:0] M_fa16_sum;
  wire [1-1:0] M_fa16_carryout;
  reg [1-1:0] M_fa16_a;
  reg [1-1:0] M_fa16_b;
  reg [1-1:0] M_fa16_c;
  fa_11 fa16 (
    .a(M_fa16_a),
    .b(M_fa16_b),
    .c(M_fa16_c),
    .sum(M_fa16_sum),
    .carryout(M_fa16_carryout)
  );
  
  reg [15:0] x;
  
  integer i;
  
  always @* begin
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      x[(i)*1+0-:1] = b[(i)*1+0-:1] ^ alufn;
    end
    M_fa1_c = alufn;
    M_fa1_a = a[0+0-:1];
    M_fa2_a = a[1+0-:1];
    M_fa3_a = a[2+0-:1];
    M_fa4_a = a[3+0-:1];
    M_fa5_a = a[4+0-:1];
    M_fa6_a = a[5+0-:1];
    M_fa7_a = a[6+0-:1];
    M_fa8_a = a[7+0-:1];
    M_fa9_a = a[8+0-:1];
    M_fa10_a = a[9+0-:1];
    M_fa11_a = a[10+0-:1];
    M_fa12_a = a[11+0-:1];
    M_fa13_a = a[12+0-:1];
    M_fa14_a = a[13+0-:1];
    M_fa15_a = a[14+0-:1];
    M_fa16_a = a[15+0-:1];
    M_fa1_b = x[0+0-:1];
    M_fa2_b = x[1+0-:1];
    M_fa3_b = x[2+0-:1];
    M_fa4_b = x[3+0-:1];
    M_fa5_b = x[4+0-:1];
    M_fa6_b = x[5+0-:1];
    M_fa7_b = x[6+0-:1];
    M_fa8_b = x[7+0-:1];
    M_fa9_b = x[8+0-:1];
    M_fa10_b = x[9+0-:1];
    M_fa11_b = x[10+0-:1];
    M_fa12_b = x[11+0-:1];
    M_fa13_b = x[12+0-:1];
    M_fa14_b = x[13+0-:1];
    M_fa15_b = x[14+0-:1];
    M_fa16_b = x[15+0-:1];
    M_fa2_c = M_fa1_carryout;
    M_fa3_c = M_fa2_carryout;
    M_fa4_c = M_fa3_carryout;
    M_fa5_c = M_fa4_carryout;
    M_fa6_c = M_fa5_carryout;
    M_fa7_c = M_fa6_carryout;
    M_fa8_c = M_fa7_carryout;
    M_fa9_c = M_fa8_carryout;
    M_fa10_c = M_fa9_carryout;
    M_fa11_c = M_fa10_carryout;
    M_fa12_c = M_fa11_carryout;
    M_fa13_c = M_fa12_carryout;
    M_fa14_c = M_fa13_carryout;
    M_fa15_c = M_fa14_carryout;
    M_fa16_c = M_fa15_carryout;
    sum[0+0-:1] = M_fa1_sum;
    sum[1+0-:1] = M_fa2_sum;
    sum[2+0-:1] = M_fa3_sum;
    sum[3+0-:1] = M_fa4_sum;
    sum[4+0-:1] = M_fa5_sum;
    sum[5+0-:1] = M_fa6_sum;
    sum[6+0-:1] = M_fa7_sum;
    sum[7+0-:1] = M_fa8_sum;
    sum[8+0-:1] = M_fa9_sum;
    sum[9+0-:1] = M_fa10_sum;
    sum[10+0-:1] = M_fa11_sum;
    sum[11+0-:1] = M_fa12_sum;
    sum[12+0-:1] = M_fa13_sum;
    sum[13+0-:1] = M_fa14_sum;
    sum[14+0-:1] = M_fa15_sum;
    sum[15+0-:1] = M_fa16_sum;
    v = ((a[15+0-:1] & x[15+0-:1] & (~M_fa16_sum)) | ((~a[15+0-:1]) & (~x[15+0-:1]) & M_fa16_sum));
    n = M_fa16_sum;
    z = ~(M_fa1_sum | M_fa2_sum | M_fa3_sum | M_fa4_sum | M_fa5_sum | M_fa6_sum | M_fa7_sum | M_fa8_sum | M_fa9_sum | M_fa10_sum | M_fa11_sum | M_fa12_sum | M_fa13_sum | M_fa14_sum | M_fa15_sum | M_fa16_sum);
  end
endmodule
