/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_1 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] result,
    output reg v
  );
  
  
  
  wire [16-1:0] M_comp1_compared;
  reg [2-1:0] M_comp1_alufn;
  reg [1-1:0] M_comp1_z;
  reg [1-1:0] M_comp1_v;
  reg [1-1:0] M_comp1_n;
  comp_5 comp1 (
    .alufn(M_comp1_alufn),
    .z(M_comp1_z),
    .v(M_comp1_v),
    .n(M_comp1_n),
    .compared(M_comp1_compared)
  );
  
  wire [16-1:0] M_sixtnbitfa1_sum;
  wire [1-1:0] M_sixtnbitfa1_v;
  wire [1-1:0] M_sixtnbitfa1_z;
  wire [1-1:0] M_sixtnbitfa1_n;
  reg [16-1:0] M_sixtnbitfa1_a;
  reg [16-1:0] M_sixtnbitfa1_b;
  reg [1-1:0] M_sixtnbitfa1_alufn;
  sixtnbitfa_6 sixtnbitfa1 (
    .a(M_sixtnbitfa1_a),
    .b(M_sixtnbitfa1_b),
    .alufn(M_sixtnbitfa1_alufn),
    .sum(M_sixtnbitfa1_sum),
    .v(M_sixtnbitfa1_v),
    .z(M_sixtnbitfa1_z),
    .n(M_sixtnbitfa1_n)
  );
  
  wire [16-1:0] M_mul1_value;
  reg [16-1:0] M_mul1_a;
  reg [16-1:0] M_mul1_b;
  mul_7 mul1 (
    .a(M_mul1_a),
    .b(M_mul1_b),
    .value(M_mul1_value)
  );
  
  wire [16-1:0] M_shift1_shifted;
  reg [2-1:0] M_shift1_alufn;
  reg [16-1:0] M_shift1_a;
  reg [16-1:0] M_shift1_b;
  shift_8 shift1 (
    .alufn(M_shift1_alufn),
    .a(M_shift1_a),
    .b(M_shift1_b),
    .shifted(M_shift1_shifted)
  );
  
  wire [16-1:0] M_boolean1_gate;
  reg [4-1:0] M_boolean1_alufn;
  reg [16-1:0] M_boolean1_a;
  reg [16-1:0] M_boolean1_b;
  boolean_9 boolean1 (
    .alufn(M_boolean1_alufn),
    .a(M_boolean1_a),
    .b(M_boolean1_b),
    .gate(M_boolean1_gate)
  );
  
  always @* begin
    v = M_sixtnbitfa1_v;
    M_sixtnbitfa1_a = a;
    M_sixtnbitfa1_b = b;
    M_mul1_a = a;
    M_mul1_b = b;
    M_comp1_v = M_sixtnbitfa1_v;
    M_comp1_n = M_sixtnbitfa1_n;
    M_comp1_z = M_sixtnbitfa1_z;
    M_shift1_a = a;
    M_shift1_b = b;
    M_boolean1_a = a;
    M_boolean1_b = b;
    M_sixtnbitfa1_alufn = alufn[0+0-:1];
    M_comp1_alufn[0+0-:1] = alufn[1+0-:1];
    M_comp1_alufn[1+0-:1] = alufn[2+0-:1];
    M_shift1_alufn[0+0-:1] = alufn[0+0-:1];
    M_shift1_alufn[1+0-:1] = alufn[1+0-:1];
    M_boolean1_alufn[0+0-:1] = alufn[0+0-:1];
    M_boolean1_alufn[1+0-:1] = alufn[1+0-:1];
    M_boolean1_alufn[2+0-:1] = alufn[2+0-:1];
    M_boolean1_alufn[3+0-:1] = alufn[3+0-:1];
    
    case (alufn)
      6'h00: begin
        result = M_sixtnbitfa1_sum;
      end
      6'h01: begin
        result = M_sixtnbitfa1_sum;
      end
      6'h02: begin
        result = M_mul1_value;
      end
      6'h18: begin
        result = M_boolean1_gate;
      end
      6'h1e: begin
        result = M_boolean1_gate;
      end
      6'h16: begin
        result = M_boolean1_gate;
      end
      6'h1a: begin
        result = a;
      end
      6'h20: begin
        result = M_shift1_shifted;
      end
      6'h21: begin
        result = M_shift1_shifted;
      end
      6'h23: begin
        result = M_shift1_shifted;
      end
      6'h33: begin
        result = M_comp1_compared;
      end
      6'h35: begin
        result = M_comp1_compared;
      end
      6'h37: begin
        result = M_comp1_compared;
      end
      default: begin
        result = 1'h0;
      end
    endcase
  end
endmodule
