/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module fa_11 (
    input a,
    input b,
    input c,
    output reg sum,
    output reg carryout
  );
  
  
  
  always @* begin
    sum = a ^ b ^ c;
    carryout = (a && b) + (c && (a ^ b));
  end
endmodule
